FROM ubuntu:14.04

RUN apt-get update && apt-get install -y \
    lighttpd \
    ruby


COPY files/lighttpd.conf /tmp/lighttpd.conf
RUN lighttpd -t -f /tmp/lighttpd.conf

EXPOSE 80

CMD ["lighttpd", "-D", "-f", "/tmp/lighttpd.conf"]
